// Code generated by SynkAdapter plugin. Do not edit this file.
package com.example.todoschedule.`data`.sync.adapter

import com.example.todoschedule.`data`.database.entity.CourseNodeEntity
import com.tap.synk.adapter.SynkAdapter
import com.tap.synk.encode.MapEncoder
import com.tap.synk.resolver.IDResolver
import javax.inject.Singleton

@Singleton
public class CourseNodeEntitySynkAdapter(
    private val idResolver: IDResolver<CourseNodeEntity> = CourseNodeEntityIDResolver(),
    private val mapEncoder: MapEncoder<CourseNodeEntity> = CourseNodeEntityMapEncoder(),
) : SynkAdapter<CourseNodeEntity>, IDResolver<CourseNodeEntity> by idResolver,
        MapEncoder<CourseNodeEntity> by mapEncoder
