// Code generated by SynkAdapter plugin. Do not edit this file.
package com.example.todoschedule.`data`.sync.adapter

import com.example.todoschedule.`data`.database.entity.OrdinaryScheduleEntity
import com.tap.synk.adapter.SynkAdapter
import com.tap.synk.encode.MapEncoder
import com.tap.synk.resolver.IDResolver
import javax.inject.Singleton

@Singleton
public class OrdinaryScheduleEntitySynkAdapter(
    private val idResolver: IDResolver<OrdinaryScheduleEntity> = OrdinaryScheduleEntityIDResolver(),
    private val mapEncoder: MapEncoder<OrdinaryScheduleEntity> = OrdinaryScheduleEntityMapEncoder(),
) : SynkAdapter<OrdinaryScheduleEntity>, IDResolver<OrdinaryScheduleEntity> by idResolver,
        MapEncoder<OrdinaryScheduleEntity> by mapEncoder
