// Code generated by SynkAdapter plugin. Do not edit this file.
package com.example.todoschedule.`data`.sync.adapter

import com.example.todoschedule.`data`.database.entity.TimeSlotEntity
import com.tap.synk.adapter.SynkAdapter
import com.tap.synk.encode.MapEncoder
import com.tap.synk.resolver.IDResolver

public class TimeSlotEntitySynkAdapter(
    private val idResolver: IDResolver<TimeSlotEntity> = TimeSlotEntityIDResolver(),
    private val mapEncoder: MapEncoder<TimeSlotEntity> = TimeSlotEntityMapEncoder(),
) : SynkAdapter<TimeSlotEntity>, IDResolver<TimeSlotEntity> by idResolver,
        MapEncoder<TimeSlotEntity> by mapEncoder
